# Generated by Django 2.0.3 on 2020-01-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8)),
                ('size', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topping1', to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topping2', to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topping3', to='orders.Toppings'),
        ),
    ]
