# Generated by Django 2.1.5 on 2020-01-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200121_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='largePrice',
            field=models.FloatField(default=65),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='smallPrice',
            field=models.FloatField(default=40),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(default=8.75),
        ),
        migrations.AlterField(
            model_name='salads',
            name='price',
            field=models.FloatField(default=8.25),
        ),
        migrations.AlterField(
            model_name='sub',
            name='largePrice',
            field=models.FloatField(default=7.95),
        ),
        migrations.AlterField(
            model_name='sub',
            name='smallPrice',
            field=models.FloatField(default=6.5),
        ),
    ]
