# Generated by Django 2.1.5 on 2020-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200121_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplate',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='dinnerplate',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pastas',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='salad',
        ),
        migrations.RemoveField(
            model_name='subs',
            name='size',
        ),
        migrations.RemoveField(
            model_name='subs',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping1',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping3',
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.TextField(default='Default', max_length=10),
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.FloatField(default=10),
        ),
        migrations.DeleteModel(
            name='DinnerPlate',
        ),
        migrations.DeleteModel(
            name='Pastas',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
    ]
