# Generated by Django 2.1.5 on 2020-02-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200121_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('orders', models.ManyToManyField(to='orders.Order')),
            ],
        ),
        migrations.AlterField(
            model_name='kind',
            name='kind',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.TextField(default='Default', max_length=11),
        ),
    ]
