# Generated by Django 2.1.5 on 2020-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200206_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='surname',
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
