# Generated by Django 2.1.5 on 2020-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200206_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='orders',
        ),
        migrations.AddField(
            model_name='ordercart',
            name='orders',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
