# Generated by Django 2.1.5 on 2020-02-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200211_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
